package com.example.takefive.data

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey


/**
 * Entity class representing an amazing thing that occurred that day recorded in a journal entry.
 *
 * @property id Primary key auto-generated by Room.
 * @property journalEntryId Foreign key referencing the associated JournalEntry.
 * @property description Description of one amazing thing that happened that day.
 */
@Entity(
    tableName = "amazing_things",
    foreignKeys = [ForeignKey(
        entity = EntryDetails::class,
        parentColumns = ["id"],
        childColumns = ["journalEntryId"],
        onDelete = ForeignKey.CASCADE
    )],
    indices = [Index("journalEntryId")]
)
data class AmazingThing(
    @PrimaryKey(autoGenerate = true) override val id: Int = 0,
    override val journalEntryId: Int,
    override val description: String
) : SubmissionItem