package com.example.takefive.data

/**
 * Interface representing an item that can be submitted in a journal entry.
 *
 * @property id Primary key auto-generated by Room.
 * @property journalEntryId Foreign key referencing the associated JournalEntry.
 * @property description Description of one amazing thing that happened that day.
 */
interface SubmissionItem {
    val id: Int
    val journalEntryId: Int
    val description: String
}