package com.example.thejournal.model

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey


/**
 * Entity class representing a thing to improve that day recorded in a journal entry.
 *
 * @property id Primary key auto-generated by Room.
 * @property journalEntryId Foreign key referencing the associated JournalEntry.
 * @property description Description of one thing to improve upon that day.
 */
@Entity(
    tableName = "things_to_improve",
    foreignKeys = [ForeignKey(
        entity = JournalEntry::class, // Parent table
        parentColumns = ["id"],       // Column(s) in the parent table
        childColumns = ["journalEntryId"], // Column(s) in the child table
        onDelete = ForeignKey.CASCADE
    )],
    indices = [Index("journalEntryId")]
)
data class ThingToImprove(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val journalEntryId: Int, // Foreign key column
    val description: String
)
