package com.example.thejournal.data

import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.room.TypeConverters
import java.time.LocalDate


/**
 * Entity class representing the journal entry details.
 *
 * @property id Primary key auto-generated by Room.
 * @property entryType Type of the journal entry (morning or evening).
 * @property date Date of the journal entry.
 */
@Entity(tableName = "journal_entries")
@TypeConverters(Converters::class)
class EntryDetails(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val date: LocalDate,
    val entryType: EntryType,
    val completed: Boolean = false
)
