package com.example.thejournal.data

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.Date


/**
 * Entity class representing a journal entry's date.
 *
 * @property id Primary key auto-generated by Room.
 * @property date Date of the journal entry.
 */
@Entity(tableName = "journal_entries")
class JournalEntry(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val date: Date
)
